FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN dpkg-reconfigure dash && dpkg --add-architecture i386
RUN apt-get update -y &&\
    apt-get install -y iproute2\
                       gcc\
                       g++ \
                       net-tools \
                       libncurses5-dev \
                       zlib1g:i386 \
                       libssl-dev \
                       flex \
                       bison \
                       libselinux1 \
                       xterm \
                       autoconf \
                       libtool \
                       texinfo \
                       zlib1g-dev \
                       gcc-multilib \
                       build-essential \
                       screen \
                       pax \
                       gawk \
                       python3 \
                       python3-pexpect \
                       python3-pip \
                       python3-git \
                       python3-jinja2 \
                       xz-utils \
                       debianutils \
                       iputils-ping \
                       libegl1-mesa \
                       libsdl1.2-dev \
                       pylint3 \
                       cpio \
                       mc \
                       sudo \
                       gdb-multiarch \
                       wget

RUN version=4.0 && build=3 && \
    mkdir ~/temp && \
    cd ~/temp && \
    wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz && \
    tar -xzvf cmake-$version.$build.tar.gz && \
    cd cmake-$version.$build/ && \
    ./bootstrap && \
    make -j$(nproc) && \
    sudo make install 

ARG USERNAME=petalinux
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
USER $USERNAME

# Копирования SDK, который нужно сформировать внутри petalinux
COPY sdk.sh /home/petalinux/sdk.sh
RUN mkdir -p /home/petalinux/sdk && \
    cd /home/petalinux/ && \
    ./sdk.sh -y -d /home/petalinux/sdk

# Применяем нужные переменные для тулчейна
COPY entrypoint.sh /usr/local/bin/ 
RUN sudo chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]